# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-01 04:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='birthdate',
            field=models.CharField(default='출생 연도를 입력해주세요', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='breed',
            field=models.CharField(default='종을 입력해주세요', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='ifneutralized',
            field=models.CharField(default='중성화 여부를 입력해주세요(함/안함)', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='ifvaccinatedrabies',
            field=models.CharField(default='광견병 백신 접종 여부를 입력해주세요(접종함/안함)', max_length=20),
        ),
    ]
