# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-01 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181101_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='address',
            field=models.CharField(default='주소를 입력해주세요\n(없으시면 없음이라고 입력해주세요)', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='contact1',
            field=models.CharField(default='비상연락망을 입력해주세요', max_length=30),
        ),
        migrations.AddField(
            model_name='post',
            name='contact2',
            field=models.CharField(default='추가 비상연락망을 입력해주세요\n(없으시면 없음이라고 입력해주세요)', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='ifvaccinatedrabies',
            field=models.CharField(default='광견병 백신 접종 여부를 입력해주세요(접종함/안함)', max_length=30),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='반려 동물 이름을 입력해주세요', max_length=20),
        ),
    ]
