# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-01 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181101_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='address',
            field=models.CharField(default='Your Home Address', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='birthdate',
            field=models.CharField(default='Birthdate of your pet', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='breed',
            field=models.CharField(default='Species of your pet', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='contact1',
            field=models.CharField(default='Your Phone Number', max_length=30),
        ),
        migrations.AlterField(
            model_name='post',
            name='contact2',
            field=models.CharField(default='Other Phone Number', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='ifneutralized',
            field=models.CharField(default='Is your pet neutralized?', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='ifvaccinatedrabies',
            field=models.CharField(default='Is your pet vaccinated against rabies?', max_length=30),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='Name of your pet', max_length=20),
        ),
    ]
