# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-01 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20181101_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='address',
            field=models.CharField(default='주소를 입력해주세요\n(없으시면 없음이라고 입력해주세요)', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='contact1',
            field=models.CharField(default='Phone number 1', max_length=30),
        ),
        migrations.AlterField(
            model_name='post',
            name='contact2',
            field=models.CharField(default='Phone number 2', max_length=50),
        ),
    ]
