# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-01 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20181101_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ownername',
            field=models.CharField(default='이름을 입력해주세요', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='registrationnumber',
            field=models.CharField(default='반려동물 등록번호를 입력해주세요\n(없으시면 없음이라고 입력해주세요)', max_length=100),
        ),
    ]
