# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-01 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20181101_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='healthwarnings',
            field=models.TextField(default='건강상의 주의 사항을 입력해주세요'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(default='특이 사항을 입력해주세요'),
        ),
    ]
