# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-03 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20181103_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='healthwarnings',
            field=models.TextField(default='반려 동물의 건강상의 주의 사항을 입력해주세요\n예) 쿠싱 증후군입니다. 수술 마취시 주의해야합니다 등\n건강상의 주의 사항은 반려동물의 실종 당시(보호자 부재시) 생길 수 있는\n사고, 질병 상황을 대비하여 의료진 및 임시 보호자에게 알리기 위함입니다.'),
        ),
    ]
